# Generated by Django 5.1.4 on 2024-12-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe1', '0005_recepie_user_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepie',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
